### ISSUE TITLE
Suggestion on Application Distribution

### ISSUE THREAD

**Issue by Ad0rableTrooper** [snjy7/mingen#1]
I would suggest you to create an executable file for your application. Well there is a little chance for your user, having Python installed in their device, but it's a good practice to distribute an application in an executable file.

You can do that by  installing pyinstaller using pip and then run the command in the directory where the file is located.
`pyinstaller  {filename.py}`
This will create an executable file of your application.

Cheers,
@adorabletrooper

**Comment by sanjayvs1** [comment]
I get your point but this is just a small personal project. I would have to make an executable file for all the popular operating systems.

**Comment by Ad0rableTrooper** [comment]
Well you don't have to make executable file for all operating systems...
